[project]
name = "hass-adtpulse"
version = "0.4.6"
description = "Home Assistant integration for ADT Pulse"
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
    "homeassistant==2025.8.0",
    "pre-commit>=4.2.0",
    "pyadtpulse>=1.2.11",
]

[dependency-groups]
dev = []
